### ISSUE TITLE
🐛 Bug:  Cannot start nuxt: Nuxt module should be a function: [object Object]                                                  

### ISSUE THREAD

**Issue by Mikaleb** [JoshuaKGoldberg/emoji-blast#822] opened 2024-12-08 11:53 UTC
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/emoji-blast/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Working

### Actual

```Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                                                       nuxt:tailwindcss 12:52:25 PM

 ERROR  Cannot start nuxt:  Nuxt module should be a function: @konami-emoji-blast/nuxt                                                                                                                                      12:52:25 PM

  at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.14.1592/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.14.1592/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (node_modules/.pnpm/nuxt@3.14.1592_sass-embedded@1.82.0/node_modules/nuxt/dist/index.mjs:4684:5)
  at async NuxtDevServer._load (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/dev2.mjs:1894:5)
  at async NuxtDevServer.load (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/dev2.mjs:1828:7)
  at async NuxtDevServer.init (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/dev2.mjs:1823:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/dev-child.mjs:104:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1777:7)
```

**Comment by JoshuaKGoldberg** [comment] 2024-12-08 20:40
Hey thanks for trying out the project, @Mikaleb! But other than that you're using Nuxt I don't really know what's going on in your project. Could you please provide a minimum reproduction?

https://antfu.me/posts/why-reproductions-are-required

**Comment by Mikaleb** [comment] 2024-12-09 12:52
here you go : [https://stackblitz.com/edit/nuxt-starter-o8hsftwz?file=nuxt.config.ts](https://stackblitz.com/edit/nuxt-starter-o8hsftwz?file=nuxt.config.ts)

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 15:22
Got it, thanks! Looks like something went wrong with the package publish and no files were published. 😬 that's not good. I'll fix it.

Also filed this issue on Nuxt for a more precise error: https://github.com/nuxt/nuxt/issues/30208

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 15:38
@all-contributors please add @mikaleb for bug.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by JoshuaKGoldberg** [comment] 2024-12-09 15:44
Status update: this is _partially_ fixed as of `@konami-emoji-blast/nuxt@0.0.5`. I downloaded the repro locally and confirmed `npm run install; npm run dev` makes a local site with the plugin loaded.

However, this forked forked repro has a different error: https://stackblitz.com/edit/nuxt-starter-bgde456v

```plaintext
 ERROR  Nuxt module should be a function: [object Object]                                                  10:42:41 AM

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2555:11)
  ...
```

**Comment by JoshuaKGoldberg** [comment] 2024-12-10 19:15
OK! That fixed it, thank you so much @danielroe! https://stackblitz.com/edit/nuxt-starter-bgde456v shows `@konami-emoji-blast@0.0.7` working completely.

**Comment by JoshuaKGoldberg** [comment] 2024-12-10 19:17
Progress! https://stackblitz.com/edit/nuxt-starter-bgde456v shows `@konami-emoji-blast@0.0.7` installing successfully, but then...

```plaintext
[plugin:vite:import-analysis] Failed to resolve entry for package "konami-emoji-blast". The package may have incorrect main/module/exports specified in its package.json.
/home/projects/nuxt-starter-bgde456v/node_modules/@konami-emoji-blast/nuxt/dist/runtime/composables/konami.js
```

That does reproduce for me locally. Investigating...

**Comment by JoshuaKGoldberg** [comment] 2024-12-10 19:58
Now with `@konami-emoji-blast/nuxt@0.0.9` and `konami-emoji-blast@0.5.7`:

```plaintext
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/konami-code-js/src/konami-code.js?v=a8f4b711' does not provide an export named 'default' (at initializeKonamiEmojiBlast.js?v=a8f4b711:2:8)
```

**Comment by JoshuaKGoldberg** [comment] 2024-12-10 20:47
Status update: it looks like [`konami-code-js`](https://www.npmjs.com/package/konami-code-js) doesn't support running in a true ESM module where `this` is `undefined`: https://github.com/MachinisteWeb/konami-code-js/issues/3. I sent https://github.com/MachinisteWeb/konami-code-js/pull/4 over to fix it. If it's not merged soon I can always fork `konami-code-js`, but would prefer not to.

**Comment by danielroe** [comment] 2024-12-10 21:43
It might be that adding it to `vite.optimizeDeps.include` in the form of `konami-emoji-blast > konami-code-js` might resolve the issue. (Assuming that `konami-emoji-blast` is installed as a direct dependency in the user's project but `konami-code-js` is not.)

**Comment by JoshuaKGoldberg** [comment] 2024-12-10 22:05
💡 Aha! That does fix it locally for me, thank you again @danielroe! 

```diff
export default defineNuxtConfig({
  // ...
  modules: ["@konami-emoji-blast/nuxt"],
+ vite: {
+   optimizeDeps: {
+     include: ["konami-emoji-blast > konami-code-js"]
+   }
+ }
});
```

FYI @Mikaleb, this can act as a workaround until https://github.com/MachinisteWeb/konami-code-js/issues/3 is fixed. I'll send a docs PR now to mention this temporary need.

**Closed** 2024-12-10 22:09 UTC
Labels: status: blocked, type: bug

**Comment by danielroe** [comment] 2024-12-10 22:10
(you could also do this from the module)

**Comment by Mikaleb** [comment] 2024-12-10 22:10
No rush @JoshuaKGoldberg , it was just a little something to put on my site to play with, I'm very happy to see how involved you are ! Big respect to you and @danielroe .

**Comment by JoshuaKGoldberg** [comment] 2024-12-10 22:13
> (you could also do this from the module)

Sorry, I don't follow - what do you mean?

**Comment by danielroe** [comment] 2024-12-10 22:28
like this: https://github.com/JoshuaKGoldberg/emoji-blast/pull/837/files
